import sgsicon from '../assets/images/sgsicon.png';
import bostadsbolageticon from '../assets/images/bostadsbolageticon.png';
import ernsticon from '../assets/images/ernsticon.png';
import skandiaicon from '../assets/images/skandiaicon.png';
import ivaricon from '../assets/images/ivaricon.png';
import skansesicon from '../assets/images/skansesicon.png';
import wallenstamicon from '../assets/images/wallenstamicon.png';
import poseidonicon from '../assets/images/poseidonicon.png';
import vasterstadenicon from '../assets/images/vasterstadenicon.png';
// import noviicon from './icons/noviicon.png';
// import skansesicon from './icons/skansesicon.png';


export default

[
  {
    "adresscoordinates": "Postgatan 18 Gothenburg",
    "adress": "Postgatan 18",
    "latitude": 57.70797,
    "longitude": 11.966281,
    "fastighetsbeteckning": "Nordstaden 17:4",
    "id": 1,
    "hyresvard": "SGS Studentbostäder",
    "hyresvardID": 1,
    "icon": sgsicon,
    "hemsida": "https://www.sgsstudentbostader.se",
    "streetview": "https://maps.googleapis.com/maps/api/streetview?size=280x140&location=Postgatan18Gothenburg&key=AIzaSyDofkfbg6HfKrjSWBYoVPi1KYMkfVx0RRE"
  },
  {
    "adresscoordinates": "Kronhusgatan 2C Gothenburg",
    "adress": "Kronhusgatan 2C",
    "latitude": 57.7077838,
    "longitude": 11.9620617,
    "fastighetsbeteckning": "Nordstaden 28:3",
    "id": 2,
    "hyresvard": "SGS Studentbostäder",
    "hyresvardID": 1,
    "icon": sgsicon,
    "hemsida": "https://www.sgsstudentbostader.se"
  },
  {
    "adresscoordinates": "Burggrevegatan 15 Gothenburg",
    "adress": "Burggrevegatan 15",
    "latitude": 57.7094076,
    "longitude": 11.9795004,
    "fastighetsbeteckning": "Stampen 4:41",
    "id": 3,
    "hyresvard": "SGS Studentbostäder",
    "hyresvardID": 1,
    "icon": sgsicon,
    "hemsida": "https://www.sgsstudentbostader.se"
  },
  {
    "adresscoordinates": "Andra Långgatan 21 Gothenburg",
    "adress": "Andra Långgatan 21, 23",
    "latitude": 57.6991807,
    "longitude": 11.9477092,
    "fastighetsbeteckning": "Masthugget 10:10",
    "id": 4,
    "hyresvard": "SGS Studentbostäder",
    "hyresvardID": 1,
    "icon": sgsicon,
    "hemsida": "https://www.sgsstudentbostader.se"
  },
  {
    "adresscoordinates": "Första Långgatan 12 Gothenburg",
    "adress": "Första Långgatan 12",
    "latitude": 57.6997994,
    "longitude": 11.9499047,
    "fastighetsbeteckning": "Masthugget 9:2",
    "id": 5,
    "hyresvard": "SGS Studentbostäder",
    "hyresvardID": 1,
    "icon": sgsicon,
    "hemsida": "https://www.sgsstudentbostader.se"
  },
  {
    "adresscoordinates": "Tredje Långgatan 10 Gothenburg",
    "adress": "Tredje Långgatan 10",
    "latitude": 57.698664,
    "longitude": 11.9506797,
    "fastighetsbeteckning": "Masthugget 3:4",
    "id": 6,
    "hyresvard": "SGS Studentbostäder",
    "hyresvardID": 1,
    "icon": sgsicon,
    "hemsida": "https://www.sgsstudentbostader.se"
  },
  {
    "adresscoordinates": "Norra Ågatan 1 Gothenburg",
    "adress": "Norra Ågatan 1",
    "latitude": 57.7109805,
    "longitude": 11.9898526,
    "fastighetsbeteckning": "Stampen 16:4",
    "id": 7,
    "hyresvard": "SGS Studentbostäder",
    "hyresvardID": 1,
    "icon": sgsicon,
    "hemsida": "https://www.sgsstudentbostader.se"
  },
  {
    "adresscoordinates": "Vasagatan 12 Gothenburg",
    "adress": "Vasagatan 12",
    "latitude": 57.6980241,
    "longitude": 11.9646631,
    "fastighetsbeteckning": "Vasastaden 9:10",
    "id": 8,
    "hyresvard": "SGS Studentbostäder",
    "hyresvardID": 1,
    "icon": sgsicon,
    "hemsida": "https://www.sgsstudentbostader.se"
  },
  {
    "adresscoordinates": "Kronhusgatan 10 Gothenburg",
    "adress": "Kronhusgatan 10",
    "latitude": 57.7083357,
    "longitude": 11.9656236,
    "fastighetsbeteckning": "Nordstaden 24:12",
    "id": 9,
    "hyresvard": "Bostadsbolaget",
    "hyresvardID": 2,
    "icon": bostadsbolageticon,
    "hemsida": "https://www.bostadsbolaget.se/"
  },
  {
    "adresscoordinates": "Kronhusgatan 12 Gothenburg",
    "adress": "Kronhusgatan 12",
    "latitude": 57.7083855,
    "longitude": 11.9659355,
    "fastighetsbeteckning": "Nordstaden 24:9",
    "id": 10,
    "hyresvard": "Bostadsbolaget",
    "hyresvardID": 2,
    "icon": bostadsbolageticon,
    "hemsida": "https://www.bostadsbolaget.se/"
  },
  {
    "adresscoordinates": "Kvarnbergsgatan 3 Gothenburg",
    "adress": "Kvarnbergsgatan 3-9",
    "latitude": 57.7087768,
    "longitude": 11.9635951,
    "fastighetsbeteckning": "Nordstaden 27:8",
    "id": 11,
    "hyresvard": "Bostadsbolaget",
    "hyresvardID": 2,
    "icon": bostadsbolageticon,
    "hemsida": "https://www.bostadsbolaget.se/"
  },
  // {
  //   "adresscoordinates": "Kvarnbergsgatan 11 Gothenburg",
  //   "adress": "Kvarnbergsgatan 11",
  //   "latitude": 57.7091533,
  //   "longitude": 11.9643007,
  //   "fastighetsbeteckning": "Nordstaden 27:5",
  //   "id": 12,
  //   "hyresvard": "Bostadsbolaget",
  //   "hyresvardID": 2,
  //   "icon": bostadsbolageticon,
  //   "hemsida": "https://www.bostadsbolaget.se/"
  // },
  // {
  //   "adresscoordinates": "Kvarnbergsgatan 4 Gothenburg",
  //   "adress": "Kvarnbergsgatan 4",
  //   "latitude": 57.7089167,
  //   "longitude": 11.9632182,
  //   "fastighetsbeteckning": "Nordstaden 29:4",
  //   "id": 13,
  //   "hyresvard": "Bostadsbolaget",
  //   "hyresvardID": 2,
  //   "icon": bostadsbolageticon,
  //   "hemsida": "https://www.bostadsbolaget.se/"
  // },
  // {
  //   "adresscoordinates": "Kvarnbergsgatan 6 Gothenburg",
  //   "adress": "Kvarnbergsgatan 6",
  //   "latitude": 57.709117,
  //   "longitude": 11.9636083,
  //   "fastighetsbeteckning": "Nordstaden 29:3",
  //   "id": 14,
  //   "hyresvard": "Bostadsbolaget",
  //   "hyresvardID": 2,
  //   "icon": bostadsbolageticon,
  //   "hemsida": "https://www.bostadsbolaget.se/"
  // },
  // {
  //   "adresscoordinates": "Kvarnbergsgatan 8 Gothenburg",
  //   "adress": "Kvarnbergsgatan 8-10",
  //   "latitude": 57.7091332,
  //   "longitude": 11.9636055,
  //   "fastighetsbeteckning": "Nordstaden 30:2",
  //   "id": 15,
  //   "hyresvard": "Bostadsbolaget",
  //   "hyresvardID": 2,
  //   "icon": bostadsbolageticon,
  //   "hemsida": "https://www.bostadsbolaget.se/"
  // },
  // {
  //   "adresscoordinates": "Kvarnbergsgatan 12 Gothenburg",
  //   "adress": "Kvarnbergsgatan 12",
  //   "latitude": 57.7091924,
  //   "longitude": 11.964085,
  //   "fastighetsbeteckning": "Nordstaden 31:2",
  //   "id": 16,
  //   "hyresvard": "Bostadsbolaget",
  //   "hyresvardID": 2,
  //   "icon": bostadsbolageticon,
  //   "hemsida": "https://www.bostadsbolaget.se/"
  // },
  // {
  //   "adresscoordinates": "Mjölnaregatan 3 Gothenburg",
  //   "adress": "Mjölnaregatan 3A-B",
  //   "latitude": 57.7091328,
  //   "longitude": 11.9631685,
  //   "fastighetsbeteckning": "Nordstaden 29:3",
  //   "id": 17,
  //   "hyresvard": "Bostadsbolaget",
  //   "hyresvardID": 2,
  //   "icon": bostadsbolageticon,
  //   "hemsida": "https://www.bostadsbolaget.se/"
  // },
  // {
  //   "adresscoordinates": "Mjölnaregatan 4 Gothenburg",
  //   "adress": "Mjölnaregatan 4",
  //   "latitude": 57.7091766,
  //   "longitude": 11.9632925,
  //   "fastighetsbeteckning": "Nordstaden 30:2",
  //   "id": 18,
  //   "hyresvard": "Bostadsbolaget",
  //   "hyresvardID": 2,
  //   "icon": bostadsbolageticon,
  //   "hemsida": "https://www.bostadsbolaget.se/"
  // },
  // {
  //   "adresscoordinates": "Nedre Kvarnbergsgatan 4 Gothenburg",
  //   "adress": "Nedre Kvarnbergsgatan 4-10",
  //   "latitude": 57.7090755,
  //   "longitude": 11.9646562,
  //   "fastighetsbeteckning": "Nordstaden 26:4",
  //   "id": 19,
  //   "hyresvard": "Bostadsbolaget",
  //   "hyresvardID": 2,
  //   "icon": bostadsbolageticon,
  //   "hemsida": "https://www.bostadsbolaget.se/"
  // },
  // {
  //   "adresscoordinates": "Nedre Kvarnbergsgatan 12 Gothenburg",
  //   "adress": "Nedre Kvarnbergsgatan 12-22",
  //   "latitude": 57.7085136,
  //   "longitude": 11.9646432,
  //   "fastighetsbeteckning": "Nordstaden 23:9",
  //   "id": 20,
  //   "hyresvard": "Bostadsbolaget",
  //   "hyresvardID": 2,
  //   "icon": bostadsbolageticon,
  //   "hemsida": "https://www.bostadsbolaget.se/"
  // },
  // {
  //   "adresscoordinates": "Sankt Eriksgatan 2A Gothenburg",
  //   "adress": "Sankt Eriksgatan 2A-B",
  //   "latitude": 57.7093989,
  //   "longitude": 11.9632095,
  //   "fastighetsbeteckning": "Nordstaden 30:1",
  //   "id": 21,
  //   "hyresvard": "Bostadsbolaget",
  //   "hyresvardID": 2,
  //   "icon": bostadsbolageticon,
  //   "hemsida": "https://www.bostadsbolaget.se/"
  // },
  {
    "adresscoordinates": "Torggatan 12 Gothenburg",
    "adress": "Torggatan 12",
    "latitude": 57.7086609,
    "longitude": 11.9654485,
    "fastighetsbeteckning": "Nordstaden 24:9",
    "id": 22,
    "hyresvard": "Bostadsbolaget",
    "hyresvardID": 2,
    "icon": bostadsbolageticon,
    "hemsida": "https://www.bostadsbolaget.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 2A Gothenburg",
    "adress": "Övre Spannmålsgatan 2A-B",
    "latitude": 57.7089448,
    "longitude": 11.9626629,
    "fastighetsbeteckning": "Nordstaden 29:1",
    "id": 23,
    "hyresvard": "Bostadsbolaget",
    "hyresvardID": 2,
    "icon": bostadsbolageticon,
    "hemsida": "https://www.bostadsbolaget.se/"
  },
  // {
  //   "adresscoordinates": "Övre Spannmålsgatan 2C Gothenburg",
  //   "adress": "Övre Spannmålsgatan 2C",
  //   "latitude": 57.7088429,
  //   "longitude": 11.9629665,
  //   "fastighetsbeteckning": "Nordstaden 29:4",
  //   "id": 24,
  //   "hyresvard": "Bostadsbolaget",
  //   "hyresvardID": 2,
  //   "icon": bostadsbolageticon,
  //   "hemsida": "https://www.bostadsbolaget.se/"
  // },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Övre Spannmålsgatan 4-6",
    "latitude": 57.7087116,
    "longitude": 11.9638259,
    "fastighetsbeteckning": "Nordstaden 27:8",
    "id": 25,
    "hyresvard": "Bostadsbolaget",
    "hyresvardID": 2,
    "icon": bostadsbolageticon,
    "hemsida": "https://www.bostadsbolaget.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Kungshöjdsgatan 7",
    "latitude": 57.702121,
    "longitude": 11.959991,
    "fastighetsbeteckning": "Nordstaden 27:8",
    "id": 25,
    "hyresvard": "Bostadsbolaget",
    "hyresvardID": 2,
    "icon": bostadsbolageticon,
    "hemsida": "https://www.bostadsbolaget.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Kungsgatan 7",
    "latitude": 57.702752,
    "longitude": 11.957429,
    "fastighetsbeteckning": "Nordstaden 27:8",
    "id": 25,
    "hyresvard": "Bostadsbolaget",
    "hyresvardID": 2,
    "icon": bostadsbolageticon,
    "hemsida": "https://www.bostadsbolaget.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Engelbrektsgatan 58",
    "latitude": 57.702157,
    "longitude": 11.984319,
    "fastighetsbeteckning": "Nordstaden 27:8",
    "id": 25,
    "hyresvard": "Bostadsbolaget",
    "hyresvardID": 2,
    "icon": bostadsbolageticon,
    "hemsida": "https://www.bostadsbolaget.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Övre Husargatan 6-12",
    "latitude": 57.693592,
    "longitude": 11.957812,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Ernst Rosén",
    "hyresvardID": 3,
    "icon": ernsticon,
    "hemsida": "https://www.ernstrosen.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Vegagatan 22-38",
    "latitude": 57.694872,
    "longitude": 11.948354,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Ernst Rosén",
    "hyresvardID": 3,
    "icon": ernsticon,
    "hemsida": "https://www.ernstrosen.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Nedre Fogelbergsgatan 6",
    "latitude": 57.697044,
    "longitude": 11.964493,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Ernst Rosen",
    "hyresvardID": 3,
    "icon": ernsticon,
    "hemsida": "https://www.ernstrosen.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Nedre Fogelbergsgatan 4",
    "latitude": 57.697211,
    "longitude": 11.964339,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Ernst Rosen",
    "hyresvardID": 3,
    "icon": ernsticon,
    "hemsida": "https://www.ernstrosen.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Engelbrektsgatan 63",
    "latitude": 57.700629,
    "longitude": 11.98253,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Ernst Rosen",
    "hyresvardID": 3,
    "icon": ernsticon,
    "hemsida": "https://www.ernstrosen.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Danska vägen 74",
    "latitude": 57.711088,
    "longitude": 12.006872,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Ernst Rosen",
    "hyresvardID": 3,
    "icon": ernsticon,
    "hemsida": "https://www.ernstrosen.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Jungmansgatan 31-33",
    "latitude": 57.693259,
    "longitude": 11.946622,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Ernst Rosen",
    "hyresvardID": 3,
    "icon": ernsticon,
    "hemsida": "https://www.ernstrosen.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Carl Grimbergsgatan 13-15",
    "latitude": 57.692095,
    "longitude": 11.959773,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Skandia fastigheter",
    "hyresvardID": 6,
    "icon": skandiaicon,
    "hemsida": "https://www.skandiafastigheter.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Smedjegatan 1 C-D",
    "latitude": 57.707581,
    "longitude": 11.962012,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Skandia fastigheter",
    "hyresvardID": 6,
    "icon": skandiaicon,
    "hemsida": "https://www.skandiafastigheter.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Karl Gustavsgatan 43",
    "latitude": 57.695012,
    "longitude": 11.968589,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Skandia fastigheter",
    "hyresvardID": 6,
    "icon": skandiaicon,
    "hemsida": "https://www.skandiafastigheter.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Folkungagatan 10",
    "latitude": 57.708623,
    "longitude": 11.985248,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Skandia fastigheter",
    "hyresvardID": 6,
    "icon": skandiaicon,
    "hemsida": "https://www.skandiafastigheter.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Baldersgatan 3",
    "latitude": 57.709005,
    "longitude": 11.985776,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Skandia fastigheter",
    "hyresvardID": 6,
    "icon": skandiaicon,
    "hemsida": "https://www.skandiafastigheter.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Stampgatan 38-40",
    "latitude": 57.707932,
    "longitude": 11.985569,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Skandia fastigheter",
    "hyresvardID": 6,
    "icon": skandiaicon,
    "hemsida": "https://www.skandiafastigheter.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Jakobsdalsgatan 15",
    "latitude": 57.695192,
    "longitude": 11.999042,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Ivar Kjellberg",
    "hyresvardID": 7,
    "icon": ivaricon,
    "hemsida": "http://ikfab.kjellberg.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Påskbergsgatan 8",
    "latitude": 57.696201,
    "longitude": 11.997186,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Ivar Kjellberg",
    "hyresvardID": 7,
    "icon": ivaricon,
    "hemsida": "http://ikfab.kjellberg.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Karl Gustavsgatan 21-23",
    "latitude": 57.697401,
    "longitude": 11.967451,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Ivar Kjellberg",
    "hyresvardID": 7,
    "icon": ivaricon,
    "hemsida": "http://ikfab.kjellberg.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Vasagatan 21",
    "latitude": 57.698382,
    "longitude": 11.968866,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Ivar Kjellberg",
    "hyresvardID": 7,
    "icon": ivaricon,
    "hemsida": "http://ikfab.kjellberg.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Vegagatan 1",
    "latitude": 57.696243,
    "longitude": 11.947904,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Ivar Kjellberg",
    "hyresvardID": 7,
    "icon": ivaricon,
    "hemsida": "http://ikfab.kjellberg.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Redbergsvägen 7",
    "latitude": 57.714199,
    "longitude": 11.997877,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Ivar Kjellberg",
    "hyresvardID": 7,
    "icon": ivaricon,
    "hemsida": "http://ikfab.kjellberg.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Kastellgatan 11",
    "latitude": 57.693886,
    "longitude": 11.955237,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Ivar Kjellberg",
    "hyresvardID": 7,
    "icon": ivaricon,
    "hemsida": "http://ikfab.kjellberg.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Danska vägen 63",
    "latitude": 57.709384,
    "longitude": 12.007452,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Ivar Kjellberg",
    "hyresvardID": 7,
    "icon": ivaricon,
    "hemsida": "http://ikfab.kjellberg.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Geijersgatan 14",
    "latitude": 57.697542,
    "longitude": 11.977918,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Skanses fastigheter",
    "hyresvardID": 10,
    "icon": skansesicon,
    "hemsida": "http://www.skansesfastigheter.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Johannebergsgatan 24",
    "latitude": 57.697285,
    "longitude": 11.982921,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Skanses fastigheter",
    "hyresvardID": 10,
    "icon": skansesicon,
    "hemsida": "http://www.skansesfastigheter.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Karl Gustavsgatan 44-52",
    "latitude": 57.694516,
    "longitude": 11.969839,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Skanses fastigheter",
    "hyresvardID": 10,
    "icon": skansesicon,
    "hemsida": "http://www.skansesfastigheter.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Majorsgatan 8",
    "latitude": 57.693864,
    "longitude": 11.953733,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Skanses fastigheter",
    "hyresvardID": 10,
    "icon": skansesicon,
    "hemsida": "http://www.skansesfastigheter.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Hvitfeldtsgatan 6",
    "latitude": 57.702373,
    "longitude": 11.958216,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Skanses fastigheter",
    "hyresvardID": 10,
    "icon": skansesicon,
    "hemsida": "http://www.skansesfastigheter.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Föreningsgatan 34",
    "latitude": 57.696437,
    "longitude": 11.970422,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Skanses fastigheter",
    "hyresvardID": 10,
    "icon": skansesicon,
    "hemsida": "http://www.skansesfastigheter.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Övre Djupedalsgatan 7",
    "latitude": 57.694973,
    "longitude": 11.949939,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Wallenstam",
    "hyresvardID": 4,
    "icon": wallenstamicon,
    "hemsida": "https://www.wallenstam.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Bellmansgatan 13",
    "latitude": 57.69853,
    "longitude": 11.964483,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Wallenstam",
    "hyresvardID": 4,
    "icon": wallenstamicon,
    "hemsida": "https://www.wallenstam.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Södra vägen 29",
    "latitude": 57.699851,
    "longitude": 11.978791,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Wallenstam",
    "hyresvardID": 4,
    "icon": wallenstamicon,
    "hemsida": "https://www.wallenstam.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Friggagatan 25 A",
    "latitude": 57.711849,
    "longitude": 11.989503,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Wallenstam",
    "hyresvardID": 4,
    "icon": wallenstamicon,
    "hemsida": "https://www.wallenstam.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Guldhedstorget 1",
    "latitude": 57.689571,
    "longitude": 11.967332,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Wallenstam",
    "hyresvardID": 4,
    "icon": wallenstamicon,
    "hemsida": "https://www.wallenstam.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Götabergsgatan 16",
    "latitude": 57.699334,
    "longitude": 11.972185,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Wallenstam",
    "hyresvardID": 4,
    "icon": wallenstamicon,
    "hemsida": "https://www.wallenstam.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Skånegatan 21-23",
    "latitude": 57.700857,
    "longitude": 11.984968,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Wallenstam",
    "hyresvardID": 4,
    "icon": wallenstamicon,
    "hemsida": "https://www.wallenstam.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Örnehufvudsgatan 7",
    "latitude": 57.68787,
    "longitude": 11.984217,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Wallenstam",
    "hyresvardID": 4,
    "icon": wallenstamicon,
    "hemsida": "https://www.wallenstam.se"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Västra Skansgatan 7-13",
    "latitude": 57.698369,
    "longitude": 11.954859,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Poseidon",
    "hyresvardID": 5,
    "icon": poseidonicon,
    "hemsida": "https://poseidon.goteborg.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Frigångsgatan 6-10",
    "latitude": 57.697844,
    "longitude": 11.954008,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Poseidon",
    "hyresvardID": 5,
    "icon": poseidonicon,
    "hemsida": "https://poseidon.goteborg.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Linnégatan 28 A-B",
    "latitude": 57.69697,
    "longitude": 11.951445,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Poseidon",
    "hyresvardID": 5,
    "icon": poseidonicon,
    "hemsida": "https://poseidon.goteborg.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Mellangatan 3-7",
    "latitude": 57.699262,
    "longitude": 11.954092,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Poseidon",
    "hyresvardID": 5,
    "icon": poseidonicon,
    "hemsida": "https://poseidon.goteborg.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Västra Skansgatan 7-13",
    "latitude": 57.698369,
    "longitude": 11.954859,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Poseidon",
    "hyresvardID": 5,
    "icon": poseidonicon,
    "hemsida": "https://poseidon.goteborg.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Västra Skansgatan 7-13",
    "latitude": 57.698369,
    "longitude": 11.954859,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Poseidon",
    "hyresvardID": 5,
    "icon": poseidonicon,
    "hemsida": "https://poseidon.goteborg.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Västra Skansgatan 7-13",
    "latitude": 57.698369,
    "longitude": 11.954859,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Poseidon",
    "hyresvardID": 5,
    "icon": poseidonicon,
    "hemsida": "https://poseidon.goteborg.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Bangatan 36",
    "latitude": 57.695101,
    "longitude": 11.936167,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Västerstaden",
    "hyresvardID": 8,
    "icon": vasterstadenicon,
    "hemsida": "https://www.vasterstaden.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Baldersgatan 2 A",
    "latitude": 57.709321,
    "longitude": 11.985748,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Västerstaden",
    "hyresvardID": 8,
    "icon": vasterstadenicon,
    "hemsida": "https://www.vasterstaden.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Berzeliigatan 12-14",
    "latitude": 57.69875,
    "longitude": 11.982153,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Västerstaden",
    "hyresvardID": 8,
    "icon": vasterstadenicon,
    "hemsida": "https://www.vasterstaden.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Eklandagatan 46",
    "latitude": 57.690597,
    "longitude": 11.98864,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Västerstaden",
    "hyresvardID": 8,
    "icon": vasterstadenicon,
    "hemsida": "https://www.vasterstaden.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Hedåsgatan 3",
    "latitude": 57.700283,
    "longitude": 11.982354,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Västerstaden",
    "hyresvardID": 8,
    "icon": vasterstadenicon,
    "hemsida": "https://www.vasterstaden.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Kapellgatan 6-8",
    "latitude": 57.69379,
    "longitude": 11.971827,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Västerstaden",
    "hyresvardID": 8,
    "icon": vasterstadenicon,
    "hemsida": "https://www.vasterstaden.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Kungsportsavenyen 43",
    "latitude": 57.697982,
    "longitude": 11.97787,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Västerstaden",
    "hyresvardID": 8,
    "icon": vasterstadenicon,
    "hemsida": "https://www.vasterstaden.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Stora Nygatan 13",
    "latitude": 57.70615,
    "longitude": 11.972941,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Västerstaden",
    "hyresvardID": 8,
    "icon": vasterstadenicon,
    "hemsida": "https://www.vasterstaden.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Viktoriagatan 3",
    "latitude": 57.699073,
    "longitude": 11.964863,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Västerstaden",
    "hyresvardID": 8,
    "icon": vasterstadenicon,
    "hemsida": "https://www.vasterstaden.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Övre Fogelbergsgatan 1",
    "latitude": 57.695591,
    "longitude": 11.964617,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Västerstaden",
    "hyresvardID": 8,
    "icon": vasterstadenicon,
    "hemsida": "https://www.vasterstaden.se/"
  },
  {
    "adresscoordinates": "Övre Spannmålsgatan 4 Gothenburg",
    "adress": "Viktor Rydbergsgatan 27",
    "latitude": 57.692856,
    "longitude": 11.979168,
    "fastighetsbeteckning": "Nordstaden 22:8",
    "id": 26,
    "hyresvard": "Västerstaden",
    "hyresvardID": 8,
    "icon": vasterstadenicon,
    "hemsida": "https://www.vasterstaden.se/"
  },
]
